CREATE TABLE category
(
    id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code   VARCHAR2(50),
    name   VARCHAR2(255),
    active NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE TABLE stock_level
(
    warehouse_code VARCHAR2(50)  NOT NULL,
    sku            VARCHAR2(50)  NOT NULL,
    quantity       NUMBER(10)    DEFAULT 0 NOT NULL,
    unit_price     NUMBER(18, 2),

    CONSTRAINT pk_stock_level PRIMARY KEY (warehouse_code, sku)
);

CREATE TABLE tag
(
    id       VARCHAR2(50) PRIMARY KEY,
    label    VARCHAR2(255),
    priority NUMBER(10) DEFAULT 0 NOT NULL
);

CREATE TABLE article
(
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR2(255),
    content      CLOB,
    published_at TIMESTAMP,
    views        NUMBER(19) DEFAULT 0 NOT NULL,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    created_by   VARCHAR2(100),
    updated_by   VARCHAR2(100),
    deleted      NUMBER(1)  DEFAULT 0 NOT NULL
);
